DROP DATABASE IF EXISTS company_db;
CREATE database company_db;
USE company_db;

 CREATE TABLE DEPARTMENT (
    ID INTEGER AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID)
);

INSERT INTO DEPARTMENT (NAME)
 VALUES ("Sales");

 INSERT INTO DEPARTMENT (NAME)
 ("Accounting");

 INSERT INTO DEPARTMENT (NAME)
 ("Human-Resource");

CREATE TABLE ROLE (
  ID INTEGER AUTO_INCREMENT NOT NULL,
  TITLE  VARCHAR(30) NOT NULL, 
  SALARY DECIMAL(10,4) NOT NULL,
  DEPARTMENT_ID INTEGER NOT NULL,
  PRIMARY KEY (ID)
  
);


INSERT INTO ROLE (TITLE, SALARY, DEPARTMENT_ID)
 VALUES ("Sales Representative", 90000, 1);

INSERT INTO ROLE (TITLE, SALARY, DEPARTMENT_ID)
 VALUES ("Sales Manager", 100000, 1);

 INSERT INTO ROLE (TITLE, SALARY, DEPARTMENT_ID)
 VALUES ("Acoounting Clerk", 60000, 2);

 INSERT INTO ROLE (TITLE, SALARY, DEPARTMENT_ID)
 VALUES ("Account Manager", 80000, 2);

 INSERT INTO ROLE (TITLE, SALARY, DEPARTMENT_ID)
 VALUES ("HR Assistant", 70000, 3);

 INSERT INTO ROLE (TITLE, SALARY, DEPARTMENT_ID)
 VALUES ("HR Manager", 80000, 3);




CREATE TABLE EMPLOYEE (
  ID INTEGER AUTO_INCREMENT NOT NULL,
  FIRST_NAME VARCHAR(30) NOT NULL,
  LAST_NAME  VARCHAR(30) NOT NULL, 
  ROLE_ID INTEGER NOT NULL,
  MANAGER_ID INTEGER ,
  PRIMARY KEY (id)
);

INSERT INTO EMPLOYEE (FIRST_NAME,LAST_NAME,ROLE_ID,MANAGER_ID)
 VALUES ("Gayathiri", "Ramamoorthy", 4, null);

 INSERT INTO EMPLOYEE (FIRST_NAME,LAST_NAME,ROLE_ID,MANAGER_ID)
 VALUES ("Mathi", "Ponnusamy", 3 , 1 );

 INSERT INTO EMPLOYEE (FIRST_NAME,LAST_NAME,ROLE_ID,MANAGER_ID)
 VALUES ("Tom", "Jerry", 3 , 1 );

 INSERT INTO EMPLOYEE (FIRST_NAME,LAST_NAME,ROLE_ID,MANAGER_ID)
 VALUES ("Sathya", "Mathi", 2, null );

 INSERT INTO EMPLOYEE (FIRST_NAME,LAST_NAME,ROLE_ID,MANAGER_ID)
 VALUES ("Mike", "Jim", 1 , 4);

INSERT INTO EMPLOYEE (FIRST_NAME,LAST_NAME,ROLE_ID,MANAGER_ID)
 VALUES ("Sabari", "Mathi", 1 , 4);

 INSERT INTO EMPLOYEE (FIRST_NAME,LAST_NAME,ROLE_ID,MANAGER_ID)
 VALUES ("Amy", "Jim", 6 , null);

 INSERT INTO EMPLOYEE (FIRST_NAME,LAST_NAME,ROLE_ID,MANAGER_ID)
 VALUES ("Raj", "San", 5 , 7);

 INSERT INTO EMPLOYEE (FIRST_NAME,LAST_NAME,ROLE_ID,MANAGER_ID)
 VALUES ("Jenny", "San", 5 , 7);

