DROP DATABASE IF EXISTS company_db;
CREATE database company_db;
USE company_db;

 CREATE TABLE DEPARTMENT (
    ID INTEGER AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID)
);


CREATE TABLE ROLE (
  ID INTEGER AUTO_INCREMENT NOT NULL,
  TITLE  VARCHAR(30) NOT NULL, 
  SALARY DECIMAL(10,2) NOT NULL,
  DEPARTMENT_ID INTEGER NOT NULL,
  PRIMARY KEY (ID)
  
);


CREATE TABLE EMPLOYEE (
  ID INTEGER AUTO_INCREMENT NOT NULL,
  FIRST_NAME VARCHAR(30) NOT NULL,
  LAST_NAME  VARCHAR(30) NOT NULL, 
  ROLE_ID INTEGER NOT NULL,
  MANAGER_ID INTEGER ,
  PRIMARY KEY (id)
);



